version: "3"

services:
  db_postgres:
    networks:
      - intranet
    restart: on-failure
    image: postgres:12.1-alpine
    container_name: "postgres_intranet"
    environment:
      - POSTGRES_DB=intranet
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:docker
    volumes:
      - "./database/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

networks:
  intranet: